### ISSUE TITLE
Functions do not work if running on a computer with different odbc configuration than the default

### ISSUE THREAD

**Issue by hanase** [psrc/psrc.travelsurvey#1]
The connection to Elmer does not work on the aws-linux server because it has different odbc settings than defined in the function `elmer_connect()`. One way to solve it is to add an argument, say `connection = NULL`, to `elmer_connect()` which could be an existing connection that would be returned if non `NULL`. Otherwise a new connection is established. E.g.

```
elmer_connect <- function(connection = NULL){
    if(!is.null(connection)) return(connection)
   # rest of the function
}
```

Then for all functions that call `elmer_connect`, dots (`...`) could be added to their signature, which would be passed to `elmer_connect`. E.g. 
```
get_hhts <- function(survey, level, vars, ...){
   # some code 
   elmer_connection <- elmer_connect(...)
  # rest of the function
```
That way apps on the aws-linux server could just pass odbc connections created using different configs, e.g.
```
get_hhts(survey, level, vars, connection = my_elmer_connection)
```

**Comment by jensenmj** [comment]
Good suggestion, Hana--I've tried to implement it with commit 663e53e93440626455cf82e2e5d810cdf0777d7c. Not sure how to test with the server, so let me know if it needs reworking.
